import { GridColDef } from "@mui/x-data-grid";
import { PokemonList } from "components";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { useListOfPokemonsQuery } from "../api";
import { AppState } from "../store";

const PokemonListPage = (): React.ReactNode => {
  const [pokemons, setPokemons] = useState([]);
  const { welcomeMsg } = useSelector((state: AppState) => state.slicePokemon.clientData);
  const { isLoading, isError, isSuccess, data } = useListOfPokemonsQuery(undefined);

  useEffect((): void => {
    if (data) {
      setPokemons(data.results.map((pokemon: { name: string; url: string; id: number }, i: number) => ({ name: pokemon.name, url: pokemon.url, id: i + 1 })));
    }
  }, [data]);

  const columns: GridColDef[] = [
    { field: "id", headerName: "No.", width: 150 },
    { field: "name", headerName: "Name", width: 150 },
    { field: "url", headerName: "Url", width: 350 },
    {
      field: "link",
      headerName: "Navigation",
      width: 350,
      renderCell: (props): React.ReactNode => <Link href={`pokemon/${props.row.id}`}>{props.row.url}</Link>,
    },
  ];

  if (isLoading) {
    return <p>loading, please wait</p>;
  }

  if (isError) {
    return <p>something went wrong</p>;
  }

  if (isSuccess) {
    return (
      <>
        <Head>
          <title>Pokemon Details page</title>
          <meta
            name="description"
            content="Generated by create next app"
          />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
          />
        </Head>
        <PokemonList
          welcomeMsg={welcomeMsg}
          pokemons={pokemons}
          columns={columns}
        />
      </>
    );
  }
};

export default PokemonListPage;
