import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "./../styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home(): React.ReactNode {
  const { push } = useRouter();
  function goToPokemon(): void {
    push("/pokemon");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Typography
          variant="h1"
          component="h2"
        >
          Welcome to Pokemons
        </Typography>
        <Button
          type="button"
          variant="contained"
          onClick={goToPokemon}
        >
          Go to Pokemons List
        </Button>
      </main>
    </>
  );
}
