import { Dispatch, UnknownAction } from "@reduxjs/toolkit";
import { Inter } from "next/font/google";
import Head from "next/head";
import { PokedexSliceProps } from "pokedex@/interface/pokedex";
import { AppState } from "pokedex@/store/app.store";
import { increment, setCount } from "pokedex@/store/pokedexSlice/pokedexSlice";
import styles from "pokedex@/styles/Home.module.css";
import { useDispatch, useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export default function Home(): React.ReactNode {
  const dispatch: Dispatch<UnknownAction> = useDispatch();
  const { name, count } = useSelector((state: AppState): PokedexSliceProps => state.pokedex);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>
          Welcome to {name}!! {count}
        </h1>
        <button onClick={() => dispatch(increment({}))}>Dispatch</button>
        <button onClick={() => dispatch(setCount({ count: 20 }))}>Update State</button>
      </main>
    </>
  );
}
